### ISSUE TITLE
DLLNotFoundException when trying to play music

### ISSUE THREAD

**Issue by MiguelGuthridge** [jmacato/Synfonia#25]
When I git clone and build the project, I manage to get it running fine, but when I try to play a song, I get the following error:

```
System.DllNotFoundException
  HResult=0x80131524
  Message=Unable to load DLL 'avutil.56': The specified module could not be found.
  Source=FFmpeg.AutoGen
  StackTrace:
   at FFmpeg.AutoGen.ffmpeg.LoadLibrary(String libraryName)
   at FFmpeg.AutoGen.ffmpeg.<>c__DisplayClass5_0.<.cctor>b__0(String name)
   at FFmpeg.AutoGen.ffmpeg.<>c.<.cctor>b__5_601(UInt64 size)
   at FFmpeg.AutoGen.ffmpeg.av_malloc(UInt64 size)
   at SharpAudio.Codec.FFmpeg.FFmpegDecoder.Ffmpeg_Initialize()
   at SharpAudio.Codec.FFmpeg.FFmpegDecoder..ctor(Stream src)
   at SharpAudio.Codec.SoundStream..ctor(Stream stream, SoundSink sink, Boolean autoDisposeSink)
   at Synfonia.Backend.DiscChanger.LoadTrack(Track track) in C:\Users\migue\Source\Synfonia\Synfonia.Backend\DiscChanger.cs:line 285
   at Synfonia.Backend.DiscChanger.<PreloadNext>b__50_0() in C:\Users\migue\Source\Synfonia\Synfonia.Backend\DiscChanger.cs:line 225
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
```

I'm kinda using this to ensure that I have Avalonia installed correctly with all the required files, so if I could get a pointer towards anything I might have missed, that'd be awesome!

**Comment by jmacato** [comment]
Hi! we have some issues with ffmpeg binaries right now, sadly me and @danwalmsley dont have time to maintain this project right now :( hopefully by the end of the year things will be better

**Comment by MiguelGuthridge** [comment]
That's fair, is there a commit that I can check out to where it'll work? If not all good! It's still really cool seeing how it all works!

**Comment by jmacato** [comment]
Actually the master branch will work; may i ask what is your current OS/Architecture?

**Comment by MiguelGuthridge** [comment]
I'm on Windows 10 (20H2), with an Intel Core i7-10750H. Am I just missing some dependencies with FFMpeg?

**Comment by jmacato** [comment]
yes, i think you need to place the ffmpeg binaries to the path where the synfonia binary is, then it should work without issue (fingers crossed)

**Comment by MiguelGuthridge** [comment]
I mean.... I have ffmpeg in the path variable so I'd expect it to work fine... that's just the ffmpeg.exe binaries though...
![image](https://user-images.githubusercontent.com/31365175/117541218-318e0880-b056-11eb-996b-d69b86462ed1.png)

**Comment by jmacato** [comment]
yeah you need  https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full-shared.7z and extract the `lib` files to the synfonia binary directory

**Comment by MiguelGuthridge** [comment]
So that version definitely has things that my build didn't, but I still can't get it to play things. The `lib` folder doesn't seem to have anything called `avutil.56`, although it does have an `avutil.lib` and an `avutil-56.def`. In this `bin` folder, there's now a DLL called `avutil-56.dll`, but this isn't the right thing (notice the dash as opposed to a dot). Renaming it doesn't fix the error, and nor does removing the `.dll` file extension. I'm very confused hahahaha.
